### ISSUE TITLE
/etc/minio/ not created and not used

### ISSUE THREAD

**Issue by benbro** [minio/minio-systemd#1]
Starting the service fail on the /etc/minio assertion:
https://github.com/minio/minio-systemd/blob/master/minio.service#L6

So either the assertion isn't needed or the README should tell us to create it.

A pervious version of the script defined --config-dir:
https://github.com/minio/minio/commit/a1621986233e3b7905fa13128b3afa43ea461ce6#diff-a5c6cac67112fb70128aa7c00a7a8977R26

Do we need both /etc/default/minio and /etc/minio?
What config options should go into config-dir?

**Comment by harshavardhana** [comment]
> Do we need both /etc/default/minio and /etc/minio?
> What config options should go into config-dir?

config-dir is created properly by minio upon fresh start and used subsequently.  "/etc/default/minio" is where you can override certain behavior and also being able to specify MINIO_VOLUMES. 

Does that make sense? ```AssertPathExists=/etc/minio/``` should be removed.

**Comment by harshavardhana** [comment]
Fixed in master.
