### ISSUE TITLE
Insecure credentials in /etc/default/minio

### ISSUE THREAD

**Issue by benbro** [minio/minio-systemd#2]
Files under /etc/default have 0644 mod by default and are readable by all users.
Can we move the credentials to /etc/minio/minio.conf and update the systemd script to use it?

**Comment by harshavardhana** [comment]
> Files under /etc/default have 0644 mod by default and are readable by all users.
> Can we move the credentials to /etc/minio/minio.conf and update the systemd script to use it?

You don't need to add credentials in this file instead you can just let `minio server` load it from `/root/.minio/config.json`

**Comment by benbro** [comment]
The [README](https://github.com/minio/minio-systemd/blob/master/README.md#create-default-configuration) suggests to put the secret in /etc/default/minio which is a bad practice.
I think the instruction should be to put the secret in /root/.minio/config.json instead.

I would expect the content of  /root/.minio/ to be under /etc/minio/ on Debian and Ubuntu but this will probably be the case if official deb packages will be released.

This issue can be closed if you are ok with the secret in a file with public read permissions.

**Comment by harshavardhana** [comment]
> I would expect the content of /root/.minio/ to be under /etc/minio/ on Debian and Ubuntu but this will probably be the case if official deb packages will be released.

For that to happen you have to use "--config-dir" as MINIO_OPTS otherwise there is no real need. Let me remove the suggestion for access keys in `/etc/default/minio`

**Comment by benbro** [comment]
It might be useful to add a comment about the default .minio config folder which will be at
MINIO_VOLUMES/.minio/

**Comment by harshavardhana** [comment]
> It might be useful to add a comment about the default .minio config folder which will be at
> MINIO_VOLUMES/.minio/

It won't be at MINIO_VOLUMES it will be at ``$HOME/.minio/config.json` - updated the docs Thanks @benbro.
